name: fernandogg

services:
  postgres:
    image: postgres
    container_name: fernandogg-postgres
    environment:
      POSTGRES_DB: fernandogg
      POSTGRES_USER: fernando
      POSTGRES_PASSWORD: change_this
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - fernandogg_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  fernandogg_postgres_data: